version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: vilson
      MONGO_INITDB_ROOT_PASSWORD: 102030

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vilson
      ME_CONFIG_MONGODB_ADMINPASSWORD: 102030
      ME_CONFIG_MONGODB_URL: mongodb://vilson:102030@mongo:27017/
